# Generated by Django 4.1.5 on 2023-01-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_refeicao_opcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='idade',
            field=models.DateTimeField(),
        ),
    ]
